### ISSUE TITLE
Issue when following the installation of gmsafir guide

### ISSUE THREAD

**Issue by kylelazzaro** [gmsafir/gmsafir#15] opened 2022-05-26 15:14 UTC
I'm working my way through the installation guide for gmsafir and I am having an issue at section 4 when I try the import gmsh command to confirm the gmsh install.

![image](https://user-images.githubusercontent.com/106332165/170517794-513f1c79-b4ef-4ae0-9730-2261620a16a6.png)

When I eventually try to run gmsafir it will appear to start than instantly close.

Any advice is really appreciated.

**Comment by gmsafir** [comment] 2022-05-27 09:00
In the install of gmsh, did you type one of those lines:
pip install -i https://gmsh.info/python-packages --force-reinstall --no-cache-dir gmsh-dev
or 
python -m pip install -i https://gmsh.info/python-packages --force-reinstall --no-cache-dir gmsh-dev
?

If not, please redo with one of those two lines

**Comment by kylelazzaro** [comment] 2022-05-27 18:53
I tried both variants just incase, but the issue still persists

![image](https://user-images.githubusercontent.com/106332165/170773029-dbc40d0d-06cf-4337-9fe3-e27e3e5c9d67.png)

**Comment by gmsafir** [comment] 2022-05-28 16:39
Please, try upgrading the ctypes package, by running:
pip install ctypes --upgrade

**Comment by gmsafir** [comment] 2022-07-04 13:25
Hi, the same issue was recently reported by another person, and in fact the "ctypes' python package cannot be upgraded, since it is a built-in package.
The problem indeed comes from this python package "ctypes", since it has been refactored since version 3.8 (independently from gmsh).

I only see an ugly way to solve it: you need to edit the following file (with your favorite text editor): 

"C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py",
  
by changing line 364, From:

if '/' in name or '\\' in name:

To:

if name is not None and ('/' in name or '\\' in name):

  

Please, keep a note of this core modification, which will probably need to be redone if you later upgrade python to a new version.

**Comment by eaat10** [comment] 2022-10-03 22:07
Hi, 

I'm having exactly the same problem. I downloaded successfully the gmsh but I'm not able to import it. I already tried to reinstall it or update de ctype but it is not possible.
![image](https://user-images.githubusercontent.com/114955145/193694167-2ffec7bb-46e2-41bb-aae4-3c7a48d6cffc.png)
I also tried to change the ctype code by hand but I couldn't find it 
![image](https://user-images.githubusercontent.com/114955145/193694534-bfea8dfe-1065-40d4-8048-b78462a6316d.png)
Please help me! 
Thanks in advance

**Comment by gmsafir** [comment] 2022-10-19 09:56
Can you try with "python.exe m pip install -i https://gmsh.info/python-packages-dev --force-reinstall --no-cache-dir gmsh" ?
The gmsh and gmsh-dev packages have now been merged

**Comment by eaat10** [comment] 2022-10-21 08:46
It is not working yet. I tried to force the installation but then I have problems importing gmsh
![image](https://user-images.githubusercontent.com/114955145/197154008-cf4847d8-7c0a-4964-a774-5f6af728a3e9.png)

**Comment by gmsafir** [comment] 2022-10-26 05:27
Your recurrent problem with 'NoneType' is not iterable comes from python version >3.7. For an unclear reason, python>3.7 works on the majority of PCs, and does not work very rarely.
Manually changing the code of ctypes sometimes work and also for unclear reason does not work, only for your case.
Another way to treat the problem is to install python3.7. The best is to remove first python3.10 and then install python3.7, only possible if you don't use python3.10 for other purposes. Otherwise you keep python3.10 installed when installing python3.7, but you call python3.7 to run GmSAFIR.

**Comment by gmsafir** [comment] 2022-10-26 11:35
A last try with the python version: can you try with python3.5?

**Comment by eaat10** [comment] 2022-10-26 13:09
Hi! I tried with python 3.6.8 and it worked. Thanks for your help

**Comment by gmsafir** [comment] 2022-10-26 13:18
Great, thanks for your patience and pugnacity!

**Closed** 2022-10-27 11:52 UTC

**Comment by kowalskiw** [comment] 2022-12-13 12:29
Hi,

I know that the issue is closed, but I found the other workaround for this problem and probably the source of it.

In my case this error was referred strictly to the fact that I have installed Python only for my local user and locations of libraries are a little messed in that case. `gmsh` was looking for the DLL in few different locations but neither was the good one.


1. My actual path to the modules (`.py`):
```C:\Users\wkowalski\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages```

2. My actual path to libraries (`.dll`, `.lib`, ...):
```C:\Users\wkowalski\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\lib\```

3. Where gmsh was trying to find its DLL:
```C:\Users\wkowalski\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\gmsh-4.11.dll```
```C:\Users\wkowalski\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Lib\gmsh-4.11.dll```
```C:\Users\wkowalski\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gmsh-4.11.dll```
```C:\Users\wkowalski\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gmsh-4.11.dll\lib```
and two trys of finding DLL with `ctypes.util.find_library()`, which according to ctypes docs should not work on Windows anyway (https://docs.python.org/2/library/ctypes.html#finding-shared-libraries).

Finally I resolved this issue with correcting `libdir` in `gmsh.py` (line 32). For example you can add the following line (as the 33rd): `libdir = os.path.dirname(libdir)`. This solution doesn't affect any other packages than gmsh, which causes the problem and do work on Python 3.10, Windows 10.

I hope this will help.
