### ISSUE TITLE
GmSAFIR shuts down when opening a file

### ISSUE THREAD

**Issue by marpitt** [gmsafir/gmsafir#10] opened 2022-04-12 15:35 UTC
I had this error today earlier. When i open a .geo file, GmSafir shuts down instantly. The same file worked yesterday. Then i made a new file, copied the geometrie part from the old .geo file and it worked again. I added some physical groups, i closed GmSAFIR, I started it again, i opened the current file and it worked. 
Now, an hour later i have the same Error with the new file again. I did not changing something, exept  that i created a 2D mesh and tried to open it afterwards. When i open the .geo file now, GmSAFIR shuts down. What could be the issue here?
[Q7.txt](https://github.com/gmsafir/gmsafir/files/8474366/Q7.txt)

**Comment by gmsafir** [comment] 2022-04-13 05:23
Hi, the file opens successuflly on my side. Download the newest version of gmsafir.py and redo the addition of physical groups. As soon as you get a crash, upload here the 2 files (Q7.geo and Q7.g4s). This will enable a diagnosis and then a debug

**Comment by marpitt** [comment] 2022-04-13 10:35
I have the newest version and I added new physical groups. I can open the file as long as i don´t close GmSAFIR. When i close GmSAFIR, then start it again and i try to open the file afterwards, GmSAFIR crashes. It is not possible to open the file again without a crash. The only way is to create a new file in GmSAFIR, copy the script from the old project and reload the script. This way it doesn´t crash but surfaces and physical groups ar not shown in the new model and i have to redo them. When i close GmSAFIR with the new project and try to open it again i have the same problem.

[Q7-g4s.txt](https://github.com/gmsafir/gmsafir/files/8480704/Q7-g4s.txt)
[Q7-geo.txt](https://github.com/gmsafir/gmsafir/files/8480705/Q7-geo.txt)

**Comment by gmsafir** [comment] 2022-04-13 11:30
sorry, not clear how to reproduce this bug. Let us try another way, to have a more verbose crash.
Please launch GmSAFIR the "old way" in command line:
1/ go to a DOS terminal ("cmd")
2/ launch following command in the terminal : pythone.exe [full_path]/gmsafir.py  (replace full_path with the one corresponding to the location of the gmsafir.py script)
3/ then in GmSAFIR, open Q7.geo, which should crash, if I get clear your problem.

Please send a "print screen" on the errors that will appear in the terminal after the crash.

**Comment by gmsafir** [comment] 2022-04-13 19:52
First of all, Q7.geo contains a weird line:
Physical Surface("Insulation", 27) += {2, 1};
The "+" sign indicates that the physgroup with id=27 has already been assigned lines in a previous line, but the previous line does not exist!
However, "Physical Surface 27" is attributed a "Surface Material" in g4s file.
Verify the definition of this physgroup, this will remove the warnings in the command line.

However, this is not the origin of the bug that you reported.
Please, download the very last version that I uploaded just now, and retry.

**Comment by marpitt** [comment] 2022-04-21 08:55
I tried the new Version, the file still crashes. I tried different stuff and i think i could localize the problem to the user defined material. If i use the material "insulation" instead of my user defined material the file does not crash. I attach you the print screen and my user defined material. Thank you for your time
![Error](https://user-images.githubusercontent.com/103035523/164418409-380ecdf9-bdc3-4f53-8079-c72726820a7b.JPG)
[Rockwool2.txt](https://github.com/gmsafir/gmsafir/files/8529384/Rockwool2.txt)
.

**Comment by gmsafir** [comment] 2022-04-21 09:24
No, the problem does not come from your user defined file: I get it worlking properly when using this user defined file with your former case 2dtherm.geo. Here are the input files:
[2dtherm.geo.txt](https://github.com/gmsafir/gmsafir/files/8529601/2dtherm.geo.txt)
[2dtherm.g4s.txt](https://github.com/gmsafir/gmsafir/files/8529602/2dtherm.g4s.txt)
[Rockwool2.txt](https://github.com/gmsafir/gmsafir/files/8529600/Rockwool2.txt)
And here the output file:
[untitled.IN.txt](https://github.com/gmsafir/gmsafir/files/8529613/untitled.IN.txt)

The crash that you have is when you use the user defined file with Q7.geo and Q7.g4s? Please, forward me the exact set of files that generate this crash.

**Comment by marpitt** [comment] 2022-04-22 10:42
I don´t know why but the Q7 file does not crash anymore even though i changed nothing since yesterday. But i have another file that has the same problem. I attach you the whole set of files that lead to the crash.

[Q6.g4s.txt](https://github.com/gmsafir/gmsafir/files/8540220/Q6.g4s.txt)
[Q6.geo.txt](https://github.com/gmsafir/gmsafir/files/8540221/Q6.geo.txt)
[Rockwool2.txt](https://github.com/gmsafir/gmsafir/files/8540222/Rockwool2.txt)

**Comment by gmsafir** [comment] 2022-04-22 11:50
ok, the problem is not due to the user defined file. It occurs because the Q6.g4s file has been written not by the newest version of gmsafir.py, which puts in the G4S file the following incorrect definition for your material Insm for physgroup 38:  
Surface - New Material Definition : Insm = {
**Material Name : defined
Material Group Name : User**
Filename : Rockwool2.txt
Young module : 210000000000
Poisson coefficient : 0.3
}
Recreating this material with the newest version of gmsafir.py corrects the definition as follows:
Surface - New Material Definition : Insm = {
**Material Name : User-defined
Material Group Name : Generic**
Filename : Rockwool2.txt
Young module : 210000000000
Poisson coefficient : 0.3
}
which then works fine.

**Comment by gmsafir** [comment] 2022-07-04 13:55
Can we close the issue or you still have the problem ?

**Closed** 2022-09-13 13:14 UTC
